
'use server';
import { generateComposeCode, type GenerateComposeCodeInput } from '@/ai/flows/generate-compose-code';
import type { DesignComponent } from '@/types/compose-spec';
import { isContainerType } from '@/types/compose-spec'; // Import the helper
import { getRemoteConfig, isAdminInitialized } from '@/lib/firebaseAdmin';

const REMOTE_CONFIG_PARAMETER_KEY = 'COMPOSE_DESIGN_JSON';

// Interface for the nodes in the AI-specific tree
interface AiComponentTreeNode {
  id: string;
  type: string; // ComponentType or custom type string
  name: string;
  properties: Record<string, any>;
  children?: AiComponentTreeNode[];
}

// Helper to create a hierarchical structure for the AI
const buildComponentTree = (allComponents: DesignComponent[], parentId: string | null = null): AiComponentTreeNode[] => {
  return allComponents
    .filter(component => component.parentId === parentId)
    .map(component => {
      const node: AiComponentTreeNode = {
        id: component.id,
        type: component.type, // Use the actual type from DesignComponent
        name: component.name,
        properties: { ...component.properties },
      };
      // For AI, we only remove x,y from root components later. Children shouldn't have them.
      // properties are passed as is for now.

      if (isContainerType(component.type)) {
        node.children = buildComponentTree(allComponents, component.id);
      }
      return node;
    });
};


export async function generateJetpackComposeCodeAction(components: DesignComponent[]): Promise<string> {
  try {
    // Build tree starting from root components (parentId === null)
    const componentTreeForAi = buildComponentTree(components).map(rootCompNode => {
      // Remove x and y from root component properties before sending to AI
      const { x, y, ...restProperties } = rootCompNode.properties;
      return { ...rootCompNode, properties: restProperties };
    });
    const designJson = JSON.stringify(componentTreeForAi, null, 2);

    const input: GenerateComposeCodeInput = { designJson };
    const result = await generateComposeCode(input);
    return result.composeCode;
  } catch (error) {
    console.error("Error generating Jetpack Compose code:", error);
    if (error instanceof Error) {
      return `Error: ${error.message}`;
    }
    return "An unknown error occurred while generating code.";
  }
}

// Interface for the nodes in the full JSON tree (for Remote Config / View JSON)
interface FullComponentTreeNode extends DesignComponent {
  childrenComponents?: FullComponentTreeNode[];
}

export async function getDesignAsJsonAction(components: DesignComponent[]): Promise<string> {
  try {
    const buildFullComponentTree = (allComponents: DesignComponent[], currentParentId: string | null = null): FullComponentTreeNode[] => {
      return allComponents
        .filter(c => c.parentId === currentParentId)
        .map(c => {
          const node: FullComponentTreeNode = { ...c }; 
          if (isContainerType(c.type)) {
            node.childrenComponents = buildFullComponentTree(allComponents, c.id);
          }
          return node;
        });
    };
    const componentTree = buildFullComponentTree(components);
    return JSON.stringify(componentTree, null, 2);
  } catch (error) {
    console.error("Error generating design JSON:", error);
    if (error instanceof Error) {
      return `Error: ${error.message}`;
    }
    return "An unknown error occurred while generating JSON.";
  }
}

export async function publishToRemoteConfigAction(components: DesignComponent[]): Promise<{ success: boolean; message: string; version?: string }> {
  if (!isAdminInitialized()) {
    return { success: false, message: 'Firebase Admin SDK not initialized. Check server logs and FIREBASE_SERVICE_ACCOUNT_JSON.' };
  }

  const remoteConfig = getRemoteConfig();
  if (!remoteConfig) {
    return { success: false, message: 'Failed to get Remote Config instance. Firebase Admin SDK might not be properly configured.' };
  }

  try {
    const designJsonString = await getDesignAsJsonAction(components);

    // Get the current template
    const currentTemplate = await remoteConfig.getTemplate();
    
    // Update the specific parameter
    currentTemplate.parameters[REMOTE_CONFIG_PARAMETER_KEY] = {
      defaultValue: { value: designJsonString },
      description: 'Jetpack Compose UI design generated by Compose Builder.',
      valueType: 'JSON',
    };

    // Validate the template (optional, but good practice)
    await remoteConfig.validateTemplate(currentTemplate);
    
    // Publish the updated template
    const updatedTemplate = await remoteConfig.publishTemplate(currentTemplate);

    return { 
      success: true, 
      message: `Design published to Remote Config parameter "${REMOTE_CONFIG_PARAMETER_KEY}".`,
      version: updatedTemplate.version?.toString() 
    };

  } catch (error) {
    console.error("Error publishing to Firebase Remote Config:", error);
    let message = "An unknown error occurred while publishing to Remote Config.";
    if (error instanceof Error) {
      message = error.message;
    }
    // Check for common errors
    if (typeof error === 'object' && error !== null && 'errorInfo' in error) {
        const firebaseError = error as { errorInfo?: { code?: string, message?: string }};
        if (firebaseError.errorInfo?.code === 'remoteconfig/template-version-mismatch') {
            message = 'Remote Config template version mismatch. Please try again.';
        } else if (firebaseError.errorInfo?.message) {
            message = firebaseError.errorInfo.message;
        }
    }
    return { success: false, message: `Error: ${message}` };
  }
}

